### PR TITLE
Trying to create a test for the load agent functionality

### PR DESCRIPTION
**Pull request by marcuss**

### CODE REVIEW

**Comment by marcuss** [comment]
@dustinbyrne I don't want to give up writing this test, but is taking too long, I'm pretty close but there is something fundamentally wrong, it could be that the tests can not live in the same project as the maven-plugin but, before giving up I ask for help, could you take a look?

btw, I could not reproduce the described error instead I got:
esourceTest
testRegisterInvalidEmail(co.marcuss.hipcontacts.web.rest.AccountResourceTest)  Time elapsed: 0.125 sec  <<< ERROR!
java.lang.IllegalArgumentException: Missing parent Event.
        at com.appland.appmap.record.RecordingSessionGeneric.lambda$add$1(RecordingSessionGeneric.java:27)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.appland.appmap.record.RecordingSessionGeneric.add(RecordingSessionGeneric.java:27)
        at com.appland.appmap.record.RecordingSessionFileStream.add(RecordingSessionFileStream.java:49)
        at com.appland.appmap.record.Recorder.writeEvent(Recorder.java:107)
        at com.appland.appmap.record.Recorder.queueEvent(Recorder.java:156)
        at com.appland.appmap.record.Recorder.add(Recorder.java:199)
        at com.appland.appmap.process.hooks.MethodException.handle(MethodException.java:22)
        at co.marcuss.hipcontacts.web.rest.AccountResourceTest.testRegisterInvalidEmail(AccountResourceTest.java:219)

**Comment by marcuss** [comment]
The test fails because int this point:

```
    protected File getAppMapAgentJar() {
        return pluginArtifactMap.get(APPMAP_AGENT_ARTIFACT_NAME).getFile();
    }
```

the pluginArtifactMap just have 1 entry and it is the maven plugin not the app map agent.

**Comment by marcuss** [comment]
pluginArtifactMap = {LinkedHashMap@2640}  size = 33
 "com.appland:appmap-maven-plugin" -> {DefaultArtifact@2677} "com.appland:appmap-maven-plugin:maven-plugin:1.0.0:"
 "org.apache.maven:maven-plugin-api" -> {DefaultArtifact@2679} "org.apache.maven:maven-plugin-api:jar:3.6.1:runtime"
 "org.apache.maven:maven-model" -> {DefaultArtifact@2681} "org.apache.maven:maven-model:jar:3.6.1:runtime"
 "org.apache.maven:maven-artifact" -> {DefaultArtifact@2683} "org.apache.maven:maven-artifact:jar:3.6.1:runtime"
 "org.eclipse.sisu:org.eclipse.sisu.plexus" -> {DefaultArtifact@2685} "org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.3:runtime"
 "javax.enterprise:cdi-api" -> {DefaultArtifact@2687} "javax.enterprise:cdi-api:jar:1.0:runtime"
 "javax.annotation:jsr250-api" -> {DefaultArtifact@2689} "javax.annotation:jsr250-api:jar:1.0:runtime"
 "org.codehaus.plexus:plexus-utils" -> {DefaultArtifact@2691} "org.codehaus.plexus:plexus-utils:jar:3.2.0:runtime"
 "org.codehaus.plexus:plexus-classworlds" -> {DefaultArtifact@2693} "org.codehaus.plexus:plexus-classworlds:jar:2.6.0:runtime"
 "org.apache.maven:maven-core" -> {DefaultArtifact@2695} "org.apache.maven:maven-core:jar:3.5.4:runtime"
 "org.apache.maven:maven-settings" -> {DefaultArtifact@2697} "org.apache.maven:maven-settings:jar:3.5.4:runtime"
 "org.apache.maven:maven-settings-builder" -> {DefaultArtifact@2699} "org.apache.maven:maven-settings-builder:jar:3.5.4:runtime"
 "org.codehaus.plexus:plexus-interpolation" -> {DefaultArtifact@2701} "org.codehaus.plexus:plexus-interpolation:jar:1.24:runtime"
 "org.sonatype.plexus:plexus-sec-dispatcher" -> {DefaultArtifact@2703} "org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:runtime"
 "org.sonatype.plexus:plexus-cipher" -> {DefaultArtifact@2705} "org.sonatype.plexus:plexus-cipher:jar:1.4:runtime"
 "org.apache.maven:maven-builder-support" -> {DefaultArtifact@2707} "org.apache.maven:maven-builder-support:jar:3.5.4:runtime"
 "org.apache.maven:maven-repository-metadata" -> {DefaultArtifact@2709} "org.apache.maven:maven-repository-metadata:jar:3.5.4:runtime"
 "org.apache.maven:maven-model-builder" -> {DefaultArtifact@2711} "org.apache.maven:maven-model-builder:jar:3.5.4:runtime"
 "org.apache.maven:maven-resolver-provider" -> {DefaultArtifact@2713} "org.apache.maven:maven-resolver-provider:jar:3.5.4:runtime"
 "org.apache.maven.resolver:maven-resolver-impl" -> {DefaultArtifact@2715} "org.apache.maven.resolver:maven-resolver-impl:jar:1.1.1:runtime"
 "org.apache.maven.resolver:maven-resolver-api" -> {DefaultArtifact@2717} "org.apache.maven.resolver:maven-resolver-api:jar:1.1.1:runtime"
 "org.apache.maven.resolver:maven-resolver-spi" -> {DefaultArtifact@2719} "org.apache.maven.resolver:maven-resolver-spi:jar:1.1.1:runtime"
 "org.apache.maven.resolver:maven-resolver-util" -> {DefaultArtifact@2721} "org.apache.maven.resolver:maven-resolver-util:jar:1.1.1:runtime"
 "org.apache.maven.shared:maven-shared-utils" -> {DefaultArtifact@2723} "org.apache.maven.shared:maven-shared-utils:jar:3.2.1:runtime"
 "commons-io:commons-io" -> {DefaultArtifact@2725} "commons-io:commons-io:jar:2.5:runtime"
 "org.eclipse.sisu:org.eclipse.sisu.inject" -> {DefaultArtifact@2727} "org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.3:runtime"
 "com.google.inject:guice" -> {DefaultArtifact@2729} "com.google.inject:guice:jar:no_aop:4.2.0:runtime"
 "aopalliance:aopalliance" -> {DefaultArtifact@2731} "aopalliance:aopalliance:jar:1.0:runtime"
 "com.google.guava:guava" -> {DefaultArtifact@2733} "com.google.guava:guava:jar:20.0:runtime"
 "javax.inject:javax.inject" -> {DefaultArtifact@2735} "javax.inject:javax.inject:jar:1:runtime"
 "org.codehaus.plexus:plexus-component-annotations" -> {DefaultArtifact@2737} "org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:runtime"

**Comment by dustinbyrne** [comment]
Is this working in #16?

**Comment by marcuss** [comment]
@dustinbyrne yes it is, I will close this draft

**Pull request closed without merging**
